group: travis_latest
language: node_js
node_js: node
cache: yarn
env:
  global:
  - secure: qFLbzmrQ7eE9e7ALuwDrH4RB5aNUFB+/HiQ1sjMoUpZK4AzemgxGhTO8cBi+ztyH+OuyyYWlU9cUmg+f6XkGckIqIeaM+P2fTqf0dIz+6ZlUKA8cCTOya3znk1wrSkM45GFe70xoy9iqePBdmMJozTM9vs5Z3aofy8qLIoo9xtQ32A8Y6pu7n2RKCvzPn0CVSxao8+l+5KW9Sh2TQPFG2pRZEoSdzNi9btwdOtU+BrENLoPgShdgERac4s5EFEk3PZS97Lm6KWSq8OQF9A7gYxdk2z4fTS0hzrkKiu+/UZt+UQiAsrok2r1pLNC92IfovWPnfGoh9iFouc44RhboQAu48PTEJpcKC1xqxkZ5QelSsNeh5Ck1lXTyZs7vKWuB/PDonrERXkn55Rqd2a9SW5a0++IqZiqD6t5/qFg8P7kQ7wj3fXdxqHU/dg+M3ix7heBBDxjZNKy2HytE0ZcY/1B780rndqF9+7VbNPurwhGVRKEGPLSBg4m2nmHdKwukT33XpX0JeiK6SvyRVzl47IIhRX+l0wa+OudWDVVpaGwqTpFPU8jvedxWzNNuwWle4FqUkz7mb5TWDH/UWCVZWzRO4J/U/FfX7C2NYdOGWba8hattbK7OKS4fKPK15p6zb1fUQrf9sEHW0GC+Ts0advnx46I2mIcpOy4qZTwq3Us=
  - secure: Dsxxf1wTQqtK2s8tZUQLJqDmXLVRrgCuUUlTqjAPsq14iiv6O4A1pz6ayAHFutWilY+s4y9ZyHbGIbrRf71ioD6ob11zh96rl+xNX0dJRqeEm4GDmeXxiAW7Rsta36g0dtMi6hG9AmIpQwzCwlX+gepULnAr9hG8oZtr5MCgbRPLb3nncoRxp4/U715eg/uylIAEhQCAqXydsH15ybnhyEfzBEZ779CqMc6JBOyNSLgSFl3+dkGjqlGxCa31P8HL8XFhOggM+k/2Mo6AzAJswpuUCCh1XJsFzo5hO53UVtmTEZnUycSLL8D1KvfjNmGHEX9CgoSqVUHD8Sex6Dfxn5NYMAL0cqwR6zSX5bq54l2DmjjZeJuUi+shc+iRW0lIdslXmLvd3p0anzztUSfWski92E3HS/H7+lCxJvfPVJ0JvNnKtFmooLnRocPSYYBBBpq+kh4ItiFrKGzL29XtKrmA7pofXg2yP4xEpm3fGRdFB3cqe79yJzh210NlYGZ456wY1vod80V+UzZbNmXlz+XMDB+IaGaiSa7MJi3yTygXjn9/V5DMbn8jgHmMfDms5ZICfvgKT7TzNzTAJZkjrcKD1p0T7Oz3valAJ7Un7S0NcLLXTJd7Xoczv+20Elu8ODPOs/+BAdAyTVtH6AjfEaVaMASOIG692GJ+hA+U06k=
deploy:
  provider: script
  skip_cleanup: true
  script:
  - yarn release
