group: travis_latest
language: node_js
node_js: node
cache: yarn
env:
  global:
  - secure: SsVwg3zBxFXWD3lWbFtcoDwZE9pxaN+UaVvnk4rvqi2eh5KCZImP4/RJ4V+xKzsa+Bol1fVLjnUCrpXsnVlJjPGxDpIk7a/pocMqJlGIQj8v+keMyAfqt6w7YQMr+nXyaN4938eiJyIW80O1O1zLwZhN6Y4jz03kAOlVNSSHBx20d4DJRcNHkpx5zzjGM58W4gBPQDNuZnTVSRx69y4WhDwR6oj3j+k9PzAXgHo7bY+51ZQBfFNv0jf8eFwiInPELLXqVdWy2IH72mu8p95o+O6nrdN97N5ilzeHlJSLusIMNHRrYjxtiz3Sfytf9QDoXmCLhXzMNw4GZT5XPipRcjnqy+oRGL9zIboKJigbI2mYFvhfnRVEwWWW1H6LXMXuzkOnNvrFl3H8kLiSOTAfVRgv4DHxpSeVGaYcDW2Q0U6+HXgM+xiEA6vx4BVefpPMgHCBXlylAf+gWuEf2kZwESdh+ajjvRGCIE3rHb/tvcN1mKYhqXmFfSwNE17ba7GzBjnBIE7lTGatVi0HiVTI52SAnnmI5r6LIuzi9wHytMlkbOMc3gwdyyGjFTDWBxQ82ryLS7UIViYZJbtmvN23LvxeiylBdSDWXhwfgwmylmcYOrjr8iHGIC3nD7GurzbV0KGHPXQQkepjBBEq6a4c1LjTQMRcJSri9QXoU4wHO44=
  - secure: QnjVSzIChmV8oiaCv09l52W4EJ8L4T7TUB4H0eCE+L3m2rzW3oTgeLkHZZpctmWRCncsnaFDQQbKlytqGUDZp/MG8nO2QdzCl+z3zSOyYDby3LbaFwmPYccnYIVN06A7SFb/Gg3NH+Bs9G9Ma0Ccw+UXjIGRG0x4q759xUtnZN7E2lCmu7mIJMuhO6F8x/rNWwqLA8sjO8VAowKtZ5DUR6FNkIjQ3CgC1UukLkCJG74d/KoJdqdgSIXaXf0s8YO6Rg9HX56K7KSr19KwVDD3tIVr3AOHWsL9TNGkUOFiiA1rQpn6s1yAJtleDKDnKDZqfHSxTZoJnG5S3WRUuAqLmGs91P+XT5TsQktoOiYIAmZzadoTQ0ZsPCCJZinc0o6PP5rVIDmZDxJkyUoGm0c3X37jP1FnNyADr9YH562NVsm3TMGLj511omMbL6BnvDSQltLekx7GuENUyBZHK2Njr1UXSUEyin/5qgIwmQW9E2r0QQAnKABwvnPZNBzjUdvtJTgCQfYQSggVDXidofUPF+xjhUZ1Nv5NSBHPinqChUxCrl4/aeq4ObpBHgkNDKZNMDYI2WnAWbe8cnJsUOsjPX3WTnz10AUrdO7UDd1PGls+M7SqgKpFe+wulPUYOHauE35jtrejB+JvoNwBxY9/JHSm0IaH56fGWitOwXAIoV4=
deploy:
  provider: script
  skip_cleanup: true
  script:
  - yarn release
