group: travis_latest
os:
- linux
- osx
services:
- docker
language: node_js
node_js: node
cache: yarn
env:
  global:
  - secure: VLGKoLwnKe4rNlbvLAqmLQg/pdy09AKnCl2wwGEbTUxwFS1yQbp11704NqEfUqqvFc7Tq3xi0KJl4FHRV5F9RCqiE40z//PAQPLezLtekYGRt1d5jJJoFQOPH7tut2B9HLL7bvy1WKOyQlTCmEklWk3AFGF1Aenn9ky+IFXsbPU38aCXaani805O3NIKmFaLl+IykwMO/ZiKIwRbrPRu0MtGNva56vbeODbgzmPYDGPc6EQlhdjsgWSqesn2GDjZFw8XinX07ERwtHf8vorNYgw/jx9P/vIFSVEnuM05D/RsKO7+/YEJBRmvqAv+EKV/B5uE+zbwqb6SSiUulXGfvmsPLEvKdZ6kIDLvItRuOpA8z+n7U9m4l1OEtb0j2QZ0ToR/E5RDqaD1H64Ofh4Ysm3ZSiQYhJtEKhjzV7CIpzjtOiPnLV0EoCSIxrpc4w7vC0/AMdIIo+zZL+RbJbd2KS9v0s2rUihwb0w+PLYUE6VYSsmHnyr3c1eIcx2Tc7Q43amgaVnwH4oKpG4EZ9sYwk0T2Mf0yGJF8QTGmjc2SoMiruRAy+nBm23b4DwnbF8WzgKfLtbNEL4RIpvPpEegmCGDvaVwFRiSlEy45fzo4mXIee5BQp5tWtbMvH8Y6u+klEQcLxGghLOAB4q5iHAi/hGzV2g2Sg5ZBZZ51x8SINk=
  - secure: aLQO9d07hSqtRPrdvGrvY5NsliuN/0S8ugV44OiSS7q4s6o5gf+PxXP9TpBV4cO7XE+Jdta41T/ZPA8ibsNf8/ISXFZWAheeZaQ6OFPP3Q95MO6zQzGgARpVDPq1XNlo3uR+I2yJzFDgPfp8YGLGh3E+WWUjJTAQk3mhWol4dHOEmevfYXnjkYzZnAtQfK5/LdJXKJHHkrhrG28mPtCO4ODzSF3i61/12RMmEmeIDtwxet7hyzFApDuDqY+77vAJQ8Sg1ulFdTgjlgxgEZmrUW+ee7iUUOiXkzvLbC2+DqojHF5MFKTvEgwX9WjMSMGyGtFUObUQle8pB2+nXFYwy5bxamAVrnOrkePCtLYmeBdRDdyKKgjEOJCY8vGxMru4lZ/q0XSpmIR5sbq6WKPob9gsqXQ/zOcPdgFIl3tqDt2AxR5dAGwS+xAZT1nXgXw6qcBBoxpdox2hjUO7KvRLZvTKZkqKiLSLjSNNUkVCKt+FkmpXNB1BzwNG+JHzgJENLm0qPTFLVFENuyEOj7i2NN9d2BBlQ1cfG4mKl5MBLRMNduOCdeqQ/EbXbOvfHN79foNjg//Zg8AvbSm3hia4NQ3iyIIoaQn/gbSJIhpK/zzJX0uDasN7vK9PfsnGe4mxzFW15bEt+GTA2wmfYBCXPymZcezLW3VFCEoKoI3d7GM=
deploy:
  provider: script
  skip_cleanup: true
  script:
  - yarn release
